name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: configure
    - name: compile
      uses: xu-cheng/latex-action@v2
    - name: make
      run: |
        cd policies
        make all

